
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}  # required for Pro
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
      - NEPTUNE_USE_SSL=${NEPTUNE_USE_SSL:-0}
      - EXTRA_CORS_ALLOWED_ORIGINS='*'
      - LS_LOG=trace
      - CFN_VERBOSE_ERRORS=1
      - CFN_LEGACY_TEMPLATE_DEPLOYER=1
    volumes:
      - "./init/init-neptune.sh:/etc/localstack/init/ready.d/init-neptune.sh"  # ready hook
      - "${LOCALSTACK_VOLUME_DIR:-./docker-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"